<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="16" time="0.275" timestamp="2022-02-28T13:40:40.551190" hostname="DESKTOP-JO9F3EE"><testcase classname="test_First" name="test_1" time="0.001" /><testcase classname="test_First" name="test_2" time="0.001" /><testcase classname="test_First" name="test_3" time="0.001" /><testcase classname="test_calc.TestCalc" name="test_add" time="0.001" /><testcase classname="test_calc.TestCalc" name="test_divide" time="0.001" /><testcase classname="test_calc.TestCalc" name="test_multiply" time="0.000" /><testcase classname="test_calc.TestCalc" name="test_subtract" time="0.001" /><testcase classname="test_employee.TestEmployee" name="test_apply_raise" time="0.001" /><testcase classname="test_employee.TestEmployee" name="test_email" time="0.001" /><testcase classname="test_employee.TestEmployee" name="test_fullname" time="0.001" /><testcase classname="test_employee.TestEmployee" name="test_monthly_schedule" time="0.001" /><testcase classname="test_four" name="test_responsecode" time="0.001" /><testcase classname="test_second" name="test_login" time="0.001" /><testcase classname="test_second" name="test_checkout" time="0.001" /><testcase classname="test_second" name="test_logout" time="0.001" /><testcase classname="test_three.MyTestCase" name="test_something" time="0.001"><failure message="AssertionError: True != False">self = &lt;test_three.MyTestCase testMethod=test_something&gt;

    def test_something(self):
&gt;       self.assertEqual(True, False)
E       AssertionError: True != False

test_three.py:5: AssertionError</failure></testcase></testsuite></testsuites>